### ISSUE TITLE
Invite button doesn't work on Periods page in coordinator

### ISSUE THREAD

**Issue by Wouter0100** [ICT-College/stage-selector#19]
Invite knop werkt niet in Coordinator afdeling bij Periods.

**Comment by Marlinc** [comment]
Could you provide some more details or a set of steps so to follow? I'm not able to reproduce this issue at the moment

**Comment by Wouter0100** [comment]
Oops, on Periods page, not Students. 

I think its because the var `periods` is defined twice in that view.

**Comment by Marlinc** [comment]
That's it.
